import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const destinations = [
  {
    name: 'Santorini',
    country: 'Grécia',
    description: 'Ilha vulcânica famosa pelas suas casas brancas com cúpulas azuis, pôr do sol em Oia e vinhos locais únicos.',
    imageUrl: 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800',
    climate: 'temperado',
    tags: ['praia', 'luxo', 'fotografia', 'romântico', 'gastronomia'],
    latitude: 36.3932,
    longitude: 25.4615,
    featured: true,
  },
  {
    name: 'Bali',
    country: 'Indonésia',
    description: 'Ilha dos deuses com templos antigos, arrozais em terraço, praias paradisíacas e cultura espiritual única.',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
    climate: 'tropical',
    tags: ['praia', 'cultura', 'natureza', 'fotografia', 'aventura', 'espiritual'],
    latitude: -8.3405,
    longitude: 115.0920,
    featured: true,
  },
  {
    name: 'Tóquio',
    country: 'Japão',
    description: 'Metrópole futurista que combina tradição samurai com tecnologia de ponta, culinária refinada e cultura pop única.',
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'gastronomia', 'tecnologia', 'fotografia', 'compras'],
    latitude: 35.6762,
    longitude: 139.6503,
    featured: true,
  },
  {
    name: 'Maldivas',
    country: 'Maldivas',
    description: 'Arquipélago de atóis com águas cristalinas, bangalôs sobre a água e recifes de coral espetaculares.',
    imageUrl: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800',
    climate: 'tropical',
    tags: ['praia', 'luxo', 'mergulho', 'romântico', 'natureza'],
    latitude: 3.2028,
    longitude: 73.2207,
    featured: true,
  },
  {
    name: 'Paris',
    country: 'França',
    description: 'A cidade da luz com a Torre Eiffel, museus de classe mundial, moda, gastronomia e romance inigualáveis.',
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'gastronomia', 'fotografia', 'romântico', 'luxo', 'arte'],
    latitude: 48.8566,
    longitude: 2.3522,
    featured: true,
  },
  {
    name: 'Nova Iorque',
    country: 'Estados Unidos',
    description: 'A grande maçã — Times Square, Central Park, Broadway, museus icónicos e gastronomia de todo o mundo.',
    imageUrl: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'compras', 'gastronomia', 'fotografia', 'entretenimento'],
    latitude: 40.7128,
    longitude: -74.0060,
    featured: true,
  },
  {
    name: 'Lisboa',
    country: 'Portugal',
    description: 'Capital europeia com sete colinas, elétricos históricos, fado, pastéis de nata e miradouros deslumbrantes.',
    imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'gastronomia', 'fotografia', 'histórico', 'económico'],
    latitude: 38.7169,
    longitude: -9.1399,
    featured: true,
  },
  {
    name: 'Machu Picchu',
    country: 'Peru',
    description: 'Cidade inca perdida nas montanhas dos Andes, Património Mundial da UNESCO e maravilha arqueológica.',
    imageUrl: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800',
    climate: 'temperado',
    tags: ['aventura', 'cultura', 'natureza', 'histórico', 'trekking', 'fotografia'],
    latitude: -13.1631,
    longitude: -72.5450,
    featured: false,
  },
  {
    name: 'Dubai',
    country: 'Emirados Árabes Unidos',
    description: 'Cidade futurista no deserto com os maiores arranha-céus do mundo, compras de luxo e experiências únicas.',
    imageUrl: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800',
    climate: 'árido',
    tags: ['luxo', 'cidade', 'compras', 'aventura', 'arquitetura', 'gastronomia'],
    latitude: 25.2048,
    longitude: 55.2708,
    featured: true,
  },
  {
    name: 'Amsterdão',
    country: 'Países Baixos',
    description: 'Cidade dos canais com museus de arte, bicicletas, tulipas e uma vibrante cena cultural e gastronómica.',
    imageUrl: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5702?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'arte', 'gastronomia', 'fotografia', 'económico'],
    latitude: 52.3676,
    longitude: 4.9041,
    featured: false,
  },
  {
    name: 'Safari no Quénia',
    country: 'Quénia',
    description: 'Grande Migração no Maasai Mara, Big Five, pôr do sol africano e experiências culturais Maasai autênticas.',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
    climate: 'tropical',
    tags: ['aventura', 'natureza', 'fotografia', 'wildlife', 'cultura'],
    latitude: -1.2921,
    longitude: 36.8219,
    featured: false,
  },
  {
    name: 'Barcelona',
    country: 'Espanha',
    description: 'Cidade de Gaudí com a Sagrada Família, praias mediterrânicas, tapas, flamenco e vida noturna intensa.',
    imageUrl: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'praia', 'gastronomia', 'arte', 'fotografia', 'económico'],
    latitude: 41.3851,
    longitude: 2.1734,
    featured: true,
  },
  {
    name: 'Ibiza',
    country: 'Espanha',
    description: 'Ilha das Baleares famosa pelas festas, praias cristalinas, pôr do sol em Café del Mar e cidades históricas.',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    climate: 'temperado',
    tags: ['praia', 'festas', 'vida noturna', 'verão', 'música', 'fotografia'],
    latitude: 38.9067,
    longitude: 1.4206,
    featured: true,
  },
  {
    name: 'Porto',
    country: 'Portugal',
    description: 'Cidade do vinho do Porto com ribeira pitoresca, caves históricas, pontes icónicas e gastronomia autêntica.',
    imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'gastronomia', 'fotografia', 'histórico', 'económico', 'vinho'],
    latitude: 41.1579,
    longitude: -8.6291,
    featured: true,
  },
  {
    name: 'Algarve',
    country: 'Portugal',
    description: 'Sul de Portugal com praias douradas, grutas marinhas, campos de golfe e marisco fresco.',
    imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800',
    climate: 'temperado',
    tags: ['praia', 'natureza', 'gastronomia', 'golfe', 'família', 'verão'],
    latitude: 37.0194,
    longitude: -7.9304,
    featured: false,
  },
  {
    name: 'Roma',
    country: 'Itália',
    description: 'A cidade eterna com o Coliseu, Vaticano, Fontana di Trevi, gastronomia inigualável e história por cada rua.',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'histórico', 'gastronomia', 'arte', 'fotografia'],
    latitude: 41.9028,
    longitude: 12.4964,
    featured: true,
  },
  {
    name: 'Londres',
    country: 'Reino Unido',
    description: 'Capital britânica com Big Ben, Buckingham Palace, museus de classe mundial e cena cultural vibrante.',
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'arte', 'compras', 'gastronomia', 'histórico'],
    latitude: 51.5074,
    longitude: -0.1278,
    featured: true,
  },
  {
    name: 'Phuket',
    country: 'Tailândia',
    description: 'Maior ilha da Tailândia com praias tropicais, templos budistas, mercados noturnos e mergulho espetacular.',
    imageUrl: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800',
    climate: 'tropical',
    tags: ['praia', 'cultura', 'mergulho', 'gastronomia', 'aventura', 'económico'],
    latitude: 7.9519,
    longitude: 98.3381,
    featured: true,
  },
  {
    name: 'Cancún',
    country: 'México',
    description: 'Paraíso caribenho com praias brancas, ruínas maias, cenotes cristalinos e vida noturna intensa.',
    imageUrl: 'https://images.unsplash.com/photo-1590456828060-6f91f8b7de15?w=800',
    climate: 'tropical',
    tags: ['praia', 'cultura', 'aventura', 'vida noturna', 'mergulho', 'família'],
    latitude: 21.1619,
    longitude: -86.8515,
    featured: false,
  },
  {
    name: 'Rio de Janeiro',
    country: 'Brasil',
    description: 'Cidade maravilhosa com Cristo Redentor, Copacabana, samba, carnaval e natureza exuberante.',
    imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800',
    climate: 'tropical',
    tags: ['praia', 'cultura', 'música', 'aventura', 'fotografia', 'natureza'],
    latitude: -22.9068,
    longitude: -43.1729,
    featured: true,
  },
  {
    name: 'Istambul',
    country: 'Turquia',
    description: 'Cidade entre dois continentes com a Hagia Sophia, Palácio Topkapi, bazares históricos e gastronomia rica.',
    imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'histórico', 'gastronomia', 'fotografia', 'compras'],
    latitude: 41.0082,
    longitude: 28.9784,
    featured: true,
  },
  {
    name: 'Marrakech',
    country: 'Marrocos',
    description: 'Cidade imperial com medina labiríntica, souks coloridos, riads luxuosos e deserto do Saara a horas.',
    imageUrl: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=800',
    climate: 'árido',
    tags: ['cultura', 'histórico', 'gastronomia', 'compras', 'aventura', 'fotografia'],
    latitude: 31.6295,
    longitude: -7.9811,
    featured: false,
  },
  {
    name: 'Praga',
    country: 'República Checa',
    description: 'Cidade de conto de fadas com o castelo medieval, ponte Carlos, cerveja artesanal e centro histórico intacto.',
    imageUrl: 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=800',
    climate: 'frio',
    tags: ['cidade', 'histórico', 'cultura', 'fotografia', 'gastronomia', 'económico'],
    latitude: 50.0755,
    longitude: 14.4378,
    featured: false,
  },
  {
    name: 'Islândia',
    country: 'Islândia',
    description: 'Terra do fogo e gelo com auroras boreais, gêiseres, cascatas épicas, glaciares e paisagens de outro mundo.',
    imageUrl: 'https://images.unsplash.com/photo-1520769669658-f07657f5a307?w=800',
    climate: 'frio',
    tags: ['natureza', 'aventura', 'fotografia', 'auroras', 'trekking', 'único'],
    latitude: 64.9631,
    longitude: -19.0208,
    featured: true,
  },
  {
    name: 'Noruega',
    country: 'Noruega',
    description: 'Fiordes dramáticos, auroras boreais, ilhas Lofoten, aldeia de Bergen e uma das naturezas mais selvagens da Europa.',
    imageUrl: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800',
    climate: 'frio',
    tags: ['natureza', 'aventura', 'fotografia', 'auroras', 'fiordes', 'trekking'],
    latitude: 60.4720,
    longitude: 8.4689,
    featured: true,
  },
  {
    name: 'Finlândia',
    country: 'Finlândia',
    description: 'País dos mil lagos com auroras boreais em Lapónia, saunas tradicionais, Pai Natal em Rovaniemi e florestas infinitas.',
    imageUrl: 'https://images.unsplash.com/photo-1578894381163-e72c17f2d45f?w=800',
    climate: 'frio',
    tags: ['natureza', 'auroras', 'família', 'cultura', 'inverno', 'único'],
    latitude: 61.9241,
    longitude: 25.7482,
    featured: false,
  },
  {
    name: 'Canadá',
    country: 'Canadá',
    description: 'País de contrastes com as Montanhas Rochosas, Banff, Niagara Falls, florestas boreais e cidades vibrantes.',
    imageUrl: 'https://images.unsplash.com/photo-1501179691627-eeaa65ea017c?w=800',
    climate: 'frio',
    tags: ['natureza', 'aventura', 'trekking', 'fotografia', 'wildlife', 'ski'],
    latitude: 56.1304,
    longitude: -106.3468,
    featured: false,
  },
  {
    name: 'Suíça',
    country: 'Suíça',
    description: 'Alpes imponentes, ski em Zermatt e Verbier, cidades de relógio como Genebra e Zurique e chocolate artesanal.',
    imageUrl: 'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?w=800',
    climate: 'frio',
    tags: ['natureza', 'ski', 'luxo', 'aventura', 'fotografia', 'romântico'],
    latitude: 46.8182,
    longitude: 8.2275,
    featured: false,
  },
  {
    name: 'Florença',
    country: 'Itália',
    description: 'Berço do Renascimento com o David de Miguel Ângelo, Uffizi, cúpula do Brunelleschi e gastronomia toscana.',
    imageUrl: 'https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?w=800',
    climate: 'temperado',
    tags: ['cultura', 'arte', 'histórico', 'gastronomia', 'fotografia', 'romântico'],
    latitude: 43.7696,
    longitude: 11.2558,
    featured: false,
  },
  {
    name: 'Sydney',
    country: 'Austrália',
    description: 'Cidade icónica com a Ópera, Harbour Bridge, praias de surf, vida selvagem única e ambiente multicultural.',
    imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800',
    climate: 'temperado',
    tags: ['cidade', 'praia', 'cultura', 'natureza', 'aventura', 'fotografia'],
    latitude: -33.8688,
    longitude: 151.2093,
    featured: false,
  },
  {
    name: 'Singapura',
    country: 'Singapura',
    description: 'Cidade-estado futurista com Gardens by the Bay, gastronomia multicultural, compras de luxo e infraestrutura de excelência.',
    imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800',
    climate: 'tropical',
    tags: ['cidade', 'gastronomia', 'compras', 'tecnologia', 'fotografia', 'luxo'],
    latitude: 1.3521,
    longitude: 103.8198,
    featured: false,
  },
  {
    name: 'Nova Zelândia',
    country: 'Nova Zelândia',
    description: 'Paisagens de outro mundo com fiordes, glaciares, vulcões, Hobbiton e desportos radicais únicos.',
    imageUrl: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800',
    climate: 'temperado',
    tags: ['natureza', 'aventura', 'trekking', 'fotografia', 'wildlife', 'desporto'],
    latitude: -40.9006,
    longitude: 174.8860,
    featured: false,
  },
];

async function main() {
  console.log('A popular a base de dados...');

  for (const destination of destinations) {
    await prisma.destination.upsert({
      where: { id: destination.name.toLowerCase().replace(/\s+/g, '-') },
      update: destination,
      create: { id: destination.name.toLowerCase().replace(/\s+/g, '-'), ...destination },
    });
  }

  console.log(`✓ ${destinations.length} destinos criados`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
