import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const destinations = [
  // ── EXISTING ─────────────────────────────────────────────────────────────
  {
    id: 'santorini',
    name: 'Santorini',
    country: 'Grécia',
    countryCode: 'GR',
    description: 'Ilha vulcânica famosa pelas suas casas brancas com cúpulas azuis, pôr do sol em Oia e vinhos locais únicos.',
    imageUrl: 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800',
    climate: 'temperado',
    tags: ['praia', 'luxo', 'fotografia', 'romântico', 'gastronomia'],
    latitude: 36.3932, longitude: 25.4615, featured: true,
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonésia',
    countryCode: 'ID',
    description: 'Ilha dos deuses com templos antigos, arrozais em terraço, praias paradisíacas e cultura espiritual única.',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
    climate: 'tropical',
    tags: ['praia', 'cultura', 'natureza', 'fotografia', 'aventura', 'espiritual'],
    latitude: -8.3405, longitude: 115.0920, featured: true,
  },
  {
    id: 'tóquio',
    name: 'Tóquio',
    country: 'Japão',
    countryCode: 'JP',
    description: 'Metrópole futurista que combina tradição samurai com tecnologia de ponta, culinária refinada e cultura pop única.',
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'gastronomia', 'tecnologia', 'fotografia', 'compras'],
    latitude: 35.6762, longitude: 139.6503, featured: true,
  },
  {
    id: 'maldivas',
    name: 'Maldivas',
    country: 'Maldivas',
    countryCode: 'MV',
    description: 'Arquipélago de atóis com águas cristalinas, bangalôs sobre a água e recifes de coral espetaculares.',
    imageUrl: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800',
    climate: 'tropical',
    tags: ['praia', 'luxo', 'mergulho', 'romântico', 'natureza'],
    latitude: 3.2028, longitude: 73.2207, featured: true,
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'França',
    countryCode: 'FR',
    description: 'A cidade da luz com a Torre Eiffel, museus de classe mundial, moda, gastronomia e romance inigualáveis.',
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'gastronomia', 'fotografia', 'romântico', 'luxo', 'arte'],
    latitude: 48.8566, longitude: 2.3522, featured: true,
  },
  {
    id: 'nova-iorque',
    name: 'Nova Iorque',
    country: 'Estados Unidos',
    countryCode: 'US',
    description: 'A grande maçã — Times Square, Central Park, Broadway, museus icónicos e gastronomia de todo o mundo.',
    imageUrl: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'compras', 'gastronomia', 'fotografia', 'entretenimento'],
    latitude: 40.7128, longitude: -74.0060, featured: true,
  },
  {
    id: 'lisboa',
    name: 'Lisboa',
    country: 'Portugal',
    countryCode: 'PT',
    description: 'Capital europeia com sete colinas, elétricos históricos, fado, pastéis de nata e miradouros deslumbrantes.',
    imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'gastronomia', 'fotografia', 'histórico', 'económico'],
    latitude: 38.7169, longitude: -9.1399, featured: true,
  },
  {
    id: 'machu-picchu',
    name: 'Machu Picchu',
    country: 'Peru',
    countryCode: 'PE',
    description: 'Cidade inca perdida nas montanhas dos Andes, Património Mundial da UNESCO e maravilha arqueológica.',
    imageUrl: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800',
    climate: 'temperado',
    tags: ['aventura', 'cultura', 'natureza', 'histórico', 'trekking', 'fotografia'],
    latitude: -13.1631, longitude: -72.5450, featured: false,
  },
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'Emirados Árabes Unidos',
    countryCode: 'AE',
    description: 'Cidade futurista no deserto com os maiores arranha-céus do mundo, compras de luxo e experiências únicas.',
    imageUrl: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800',
    climate: 'árido',
    tags: ['luxo', 'cidade', 'compras', 'aventura', 'arquitetura', 'gastronomia'],
    latitude: 25.2048, longitude: 55.2708, featured: true,
  },
  {
    id: 'amsterdão',
    name: 'Amsterdão',
    country: 'Países Baixos',
    countryCode: 'NL',
    description: 'Cidade dos canais com museus de arte, bicicletas, tulipas e uma vibrante cena cultural e gastronómica.',
    imageUrl: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5702?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'arte', 'gastronomia', 'fotografia', 'económico'],
    latitude: 52.3676, longitude: 4.9041, featured: false,
  },
  {
    id: 'safari-no-quénia',
    name: 'Safari no Quénia',
    country: 'Quénia',
    countryCode: 'KE',
    description: 'Grande Migração no Maasai Mara, Big Five, pôr do sol africano e experiências culturais Maasai autênticas.',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
    climate: 'tropical',
    tags: ['aventura', 'natureza', 'fotografia', 'wildlife', 'cultura'],
    latitude: -1.2921, longitude: 36.8219, featured: false,
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'Espanha',
    countryCode: 'ES',
    description: 'Cidade de Gaudí com a Sagrada Família, praias mediterrânicas, tapas, flamenco e vida noturna intensa.',
    imageUrl: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'praia', 'gastronomia', 'arte', 'fotografia', 'económico'],
    latitude: 41.3851, longitude: 2.1734, featured: true,
  },
  {
    id: 'ibiza',
    name: 'Ibiza',
    country: 'Espanha',
    countryCode: 'ES',
    description: 'Ilha das Baleares famosa pelas festas, praias cristalinas, pôr do sol em Café del Mar e cidades históricas.',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    climate: 'temperado',
    tags: ['praia', 'festas', 'vida noturna', 'verão', 'música', 'fotografia'],
    latitude: 38.9067, longitude: 1.4206, featured: true,
  },
  {
    id: 'porto',
    name: 'Porto',
    country: 'Portugal',
    countryCode: 'PT',
    description: 'Cidade do vinho do Porto com ribeira pitoresca, caves históricas, pontes icónicas e gastronomia autêntica.',
    imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'gastronomia', 'fotografia', 'histórico', 'económico', 'vinho'],
    latitude: 41.1579, longitude: -8.6291, featured: true,
  },
  {
    id: 'algarve',
    name: 'Algarve',
    country: 'Portugal',
    countryCode: 'PT',
    description: 'Sul de Portugal com praias douradas, grutas marinhas, campos de golfe e marisco fresco.',
    imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800',
    climate: 'temperado',
    tags: ['praia', 'natureza', 'gastronomia', 'golfe', 'família', 'verão'],
    latitude: 37.0194, longitude: -7.9304, featured: false,
  },
  {
    id: 'roma',
    name: 'Roma',
    country: 'Itália',
    countryCode: 'IT',
    description: 'A cidade eterna com o Coliseu, Vaticano, Fontana di Trevi, gastronomia inigualável e história por cada rua.',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'histórico', 'gastronomia', 'arte', 'fotografia'],
    latitude: 41.9028, longitude: 12.4964, featured: true,
  },
  {
    id: 'londres',
    name: 'Londres',
    country: 'Reino Unido',
    countryCode: 'GB',
    description: 'Capital britânica com Big Ben, Buckingham Palace, museus de classe mundial e cena cultural vibrante.',
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'arte', 'compras', 'gastronomia', 'histórico'],
    latitude: 51.5074, longitude: -0.1278, featured: true,
  },
  {
    id: 'phuket',
    name: 'Phuket',
    country: 'Tailândia',
    countryCode: 'TH',
    description: 'Maior ilha da Tailândia com praias tropicais, templos budistas, mercados noturnos e mergulho espetacular.',
    imageUrl: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800',
    climate: 'tropical',
    tags: ['praia', 'cultura', 'mergulho', 'gastronomia', 'aventura', 'económico'],
    latitude: 7.9519, longitude: 98.3381, featured: true,
  },
  {
    id: 'cancún',
    name: 'Cancún',
    country: 'México',
    countryCode: 'MX',
    description: 'Paraíso caribenho com praias brancas, ruínas maias, cenotes cristalinos e vida noturna intensa.',
    imageUrl: 'https://images.unsplash.com/photo-1590456828060-6f91f8b7de15?w=800',
    climate: 'tropical',
    tags: ['praia', 'cultura', 'aventura', 'vida noturna', 'mergulho', 'família'],
    latitude: 21.1619, longitude: -86.8515, featured: false,
  },
  {
    id: 'rio-de-janeiro',
    name: 'Rio de Janeiro',
    country: 'Brasil',
    countryCode: 'BR',
    description: 'Cidade maravilhosa com Cristo Redentor, Copacabana, samba, carnaval e natureza exuberante.',
    imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800',
    climate: 'tropical',
    tags: ['praia', 'cultura', 'música', 'aventura', 'fotografia', 'natureza'],
    latitude: -22.9068, longitude: -43.1729, featured: true,
  },
  {
    id: 'istambul',
    name: 'Istambul',
    country: 'Turquia',
    countryCode: 'TR',
    description: 'Cidade entre dois continentes com a Hagia Sophia, Palácio Topkapi, bazares históricos e gastronomia rica.',
    imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'histórico', 'gastronomia', 'fotografia', 'compras'],
    latitude: 41.0082, longitude: 28.9784, featured: true,
  },
  {
    id: 'marrakech',
    name: 'Marrakech',
    country: 'Marrocos',
    countryCode: 'MA',
    description: 'Cidade imperial com medina labiríntica, souks coloridos, riads luxuosos e deserto do Saara a horas.',
    imageUrl: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=800',
    climate: 'árido',
    tags: ['cultura', 'histórico', 'gastronomia', 'compras', 'aventura', 'fotografia'],
    latitude: 31.6295, longitude: -7.9811, featured: false,
  },
  {
    id: 'praga',
    name: 'Praga',
    country: 'República Checa',
    countryCode: 'CZ',
    description: 'Cidade de conto de fadas com o castelo medieval, ponte Carlos, cerveja artesanal e centro histórico intacto.',
    imageUrl: 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=800',
    climate: 'frio',
    tags: ['cidade', 'histórico', 'cultura', 'fotografia', 'gastronomia', 'económico'],
    latitude: 50.0755, longitude: 14.4378, featured: false,
  },
  // ── COLD DESTINATIONS (IDs match SQL inserts — without accents) ───────────
  {
    id: 'islandia',
    name: 'Islândia',
    country: 'Islândia',
    countryCode: 'IS',
    description: 'Terra do fogo e gelo com auroras boreais, gêiseres, cascatas épicas, glaciares e paisagens de outro mundo.',
    imageUrl: 'https://images.unsplash.com/photo-1520769669658-f07657f5a307?w=800',
    climate: 'frio',
    tags: ['natureza', 'aventura', 'fotografia', 'auroras', 'trekking', 'único'],
    latitude: 64.9631, longitude: -19.0208, featured: true,
  },
  {
    id: 'noruega',
    name: 'Noruega',
    country: 'Noruega',
    countryCode: 'NO',
    description: 'Fiordes dramáticos, auroras boreais, ilhas Lofoten, aldeia de Bergen e uma das naturezas mais selvagens da Europa.',
    imageUrl: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800',
    climate: 'frio',
    tags: ['natureza', 'aventura', 'fotografia', 'auroras', 'fiordes', 'trekking'],
    latitude: 60.4720, longitude: 8.4689, featured: true,
  },
  {
    id: 'finlandia',
    name: 'Finlândia',
    country: 'Finlândia',
    countryCode: 'FI',
    description: 'País dos mil lagos com auroras boreais em Lapónia, saunas tradicionais, Pai Natal em Rovaniemi e florestas infinitas.',
    imageUrl: 'https://images.unsplash.com/photo-1578894381163-e72c17f2d45f?w=800',
    climate: 'frio',
    tags: ['natureza', 'auroras', 'família', 'cultura', 'inverno', 'único'],
    latitude: 61.9241, longitude: 25.7482, featured: false,
  },
  {
    id: 'canada',
    name: 'Canadá',
    country: 'Canadá',
    countryCode: 'CA',
    description: 'País de contrastes com as Montanhas Rochosas, Banff, Niagara Falls, florestas boreais e cidades vibrantes.',
    imageUrl: 'https://images.unsplash.com/photo-1501179691627-eeaa65ea017c?w=800',
    climate: 'frio',
    tags: ['natureza', 'aventura', 'trekking', 'fotografia', 'wildlife', 'ski'],
    latitude: 56.1304, longitude: -106.3468, featured: false,
  },
  {
    id: 'suica',
    name: 'Suíça',
    country: 'Suíça',
    countryCode: 'CH',
    description: 'Alpes imponentes, ski em Zermatt e Verbier, cidades de relógio como Genebra e Zurique e chocolate artesanal.',
    imageUrl: 'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?w=800',
    climate: 'frio',
    tags: ['natureza', 'ski', 'luxo', 'aventura', 'fotografia', 'romântico'],
    latitude: 46.8182, longitude: 8.2275, featured: false,
  },
  // ── EXISTING OTHERS ───────────────────────────────────────────────────────
  {
    id: 'florença',
    name: 'Florença',
    country: 'Itália',
    countryCode: 'IT',
    description: 'Berço do Renascimento com o David de Miguel Ângelo, Uffizi, cúpula do Brunelleschi e gastronomia toscana.',
    imageUrl: 'https://images.unsplash.com/photo-1541364983171-a8ba01e95cfc?w=800',
    climate: 'temperado',
    tags: ['cultura', 'arte', 'histórico', 'gastronomia', 'fotografia', 'romântico'],
    latitude: 43.7696, longitude: 11.2558, featured: false,
  },
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Austrália',
    countryCode: 'AU',
    description: 'Cidade icónica com a Ópera, Harbour Bridge, praias de surf, vida selvagem única e ambiente multicultural.',
    imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800',
    climate: 'temperado',
    tags: ['cidade', 'praia', 'cultura', 'natureza', 'aventura', 'fotografia'],
    latitude: -33.8688, longitude: 151.2093, featured: false,
  },
  {
    id: 'singapura',
    name: 'Singapura',
    country: 'Singapura',
    countryCode: 'SG',
    description: 'Cidade-estado futurista com Gardens by the Bay, gastronomia multicultural, compras de luxo e infraestrutura de excelência.',
    imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800',
    climate: 'tropical',
    tags: ['cidade', 'gastronomia', 'compras', 'tecnologia', 'fotografia', 'luxo'],
    latitude: 1.3521, longitude: 103.8198, featured: false,
  },
  {
    id: 'nova-zelândia',
    name: 'Nova Zelândia',
    country: 'Nova Zelândia',
    countryCode: 'NZ',
    description: 'Paisagens de outro mundo com fiordes, glaciares, vulcões, Hobbiton e desportos radicais únicos.',
    imageUrl: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800',
    climate: 'temperado',
    tags: ['natureza', 'aventura', 'trekking', 'fotografia', 'wildlife', 'desporto'],
    latitude: -40.9006, longitude: 174.8860, featured: false,
  },

  // ── NEW EUROPE ────────────────────────────────────────────────────────────
  {
    id: 'viena',
    name: 'Viena',
    country: 'Áustria',
    countryCode: 'AT',
    description: 'Capital imperial com palácios barrocos, cafés históricos, música clássica, museus de classe mundial e Prater.',
    imageUrl: 'https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'arte', 'gastronomia', 'histórico', 'música'],
    latitude: 48.2082, longitude: 16.3738, featured: false,
  },
  {
    id: 'berlim',
    name: 'Berlim',
    country: 'Alemanha',
    countryCode: 'DE',
    description: 'Capital alemã com o Muro, Portão de Brandenburgo, cena artística vibrante, museus e vida noturna única.',
    imageUrl: 'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'histórico', 'arte', 'vida noturna', 'fotografia'],
    latitude: 52.5200, longitude: 13.4050, featured: false,
  },
  {
    id: 'munique',
    name: 'Munique',
    country: 'Alemanha',
    countryCode: 'DE',
    description: 'Cidade bávara com Oktoberfest, jardins ingleses, cervejas artesanais, museus técnicos e castelos de conto de fadas.',
    imageUrl: 'https://images.unsplash.com/photo-1527090526205-befd3c7f96c9?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'gastronomia', 'histórico', 'família', 'festivais'],
    latitude: 48.1351, longitude: 11.5820, featured: false,
  },
  {
    id: 'estocolmo',
    name: 'Estocolmo',
    country: 'Suécia',
    countryCode: 'SE',
    description: 'Capital escandinava sobre ilhas com Gamla Stan medieval, museu Vasa, design nórdico e arquipélago deslumbrante.',
    imageUrl: 'https://images.unsplash.com/photo-1509356843962-db4a8dea2b93?w=800',
    climate: 'frio',
    tags: ['cidade', 'cultura', 'design', 'natureza', 'histórico', 'fotografia'],
    latitude: 59.3293, longitude: 18.0686, featured: false,
  },
  {
    id: 'copenhaga',
    name: 'Copenhaga',
    country: 'Dinamarca',
    countryCode: 'DK',
    description: 'Capital dinamarquesa com Nyhavn colorido, gastronomia de vanguarda, Tivoli histórico e cena cultural vibrante.',
    imageUrl: 'https://images.unsplash.com/photo-1513622470522-26c5d32f5c2b?w=800',
    climate: 'frio',
    tags: ['cidade', 'cultura', 'gastronomia', 'design', 'fotografia', 'família'],
    latitude: 55.6761, longitude: 12.5683, featured: false,
  },
  {
    id: 'dublin',
    name: 'Dublin',
    country: 'Irlanda',
    countryCode: 'IE',
    description: 'Capital irlandesa com pubs históricos, Guinness Storehouse, Trinity College, cliffs of Moher e natureza deslumbrante.',
    imageUrl: 'https://images.unsplash.com/photo-1558618047-3d090f7e7a8b?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'histórico', 'gastronomia', 'natureza', 'convivial'],
    latitude: 53.3498, longitude: -6.2603, featured: false,
  },
  {
    id: 'cracovia',
    name: 'Cracóvia',
    country: 'Polónia',
    countryCode: 'PL',
    description: 'Joia medieval com a Praça do Mercado, Castelo de Wawel, bairro judaico de Kazimierz e memória de Auschwitz próxima.',
    imageUrl: 'https://images.unsplash.com/photo-1512693776-3898a82e97e5?w=800',
    climate: 'frio',
    tags: ['cidade', 'histórico', 'cultura', 'arte', 'fotografia', 'económico'],
    latitude: 50.0647, longitude: 19.9450, featured: false,
  },
  {
    id: 'budapeste',
    name: 'Budapeste',
    country: 'Hungria',
    countryCode: 'HU',
    description: 'Pérola do Danúbio com o Parlamento neogótico, banhos termais, ruin bars e gastronomia húngara rica.',
    imageUrl: 'https://images.unsplash.com/photo-1541955193702-5d3e9f994b2c?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'histórico', 'gastronomia', 'fotografia', 'económico'],
    latitude: 47.4979, longitude: 19.0402, featured: false,
  },
  {
    id: 'atenas',
    name: 'Atenas',
    country: 'Grécia',
    countryCode: 'GR',
    description: 'Berço da democracia com a Acrópole e Partenão, museus arqueológicos excepcionais, tavernas e vida noturna vibrante.',
    imageUrl: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800',
    climate: 'temperado',
    tags: ['cidade', 'histórico', 'cultura', 'gastronomia', 'fotografia', 'arte'],
    latitude: 37.9838, longitude: 23.7275, featured: false,
  },
  {
    id: 'madrid',
    name: 'Madrid',
    country: 'Espanha',
    countryCode: 'ES',
    description: 'Capital espanhola com o Prado, Reina Sofía, tapas, flamenco, Retiro e a vida noturna mais animada da Europa.',
    imageUrl: 'https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'arte', 'gastronomia', 'vida noturna', 'fotografia'],
    latitude: 40.4168, longitude: -3.7038, featured: false,
  },
  {
    id: 'milao',
    name: 'Milão',
    country: 'Itália',
    countryCode: 'IT',
    description: 'Capital da moda e do design com o Duomo, Última Ceia de Da Vinci, haute cuisine e Navigli animado.',
    imageUrl: 'https://images.unsplash.com/photo-1543726076-0086af3625f2?w=800',
    climate: 'temperado',
    tags: ['cidade', 'moda', 'arte', 'gastronomia', 'compras', 'design'],
    latitude: 45.4642, longitude: 9.1900, featured: false,
  },
  {
    id: 'veneza',
    name: 'Veneza',
    country: 'Itália',
    countryCode: 'IT',
    description: 'Cidade flutuante única com canais, gôndolas, Praça de São Marcos, Carnaval e arte renascentista incomparável.',
    imageUrl: 'https://images.unsplash.com/photo-1534430480872-2ffd4e7bd80c?w=800',
    climate: 'temperado',
    tags: ['cidade', 'romântico', 'cultura', 'arte', 'histórico', 'fotografia'],
    latitude: 45.4408, longitude: 12.3155, featured: true,
  },
  {
    id: 'malta',
    name: 'Malta',
    country: 'Malta',
    countryCode: 'MT',
    description: 'Arquipélago mediterrânico com Valeta barroca, templos pré-históricos, mar azul-turquesa e história rica dos Cavaleiros.',
    imageUrl: 'https://images.unsplash.com/photo-1514104559696-53b60d36c3a3?w=800',
    climate: 'temperado',
    tags: ['praia', 'histórico', 'cultura', 'mergulho', 'fotografia', 'económico'],
    latitude: 35.9375, longitude: 14.3754, featured: false,
  },
  {
    id: 'dubrovnik',
    name: 'Dubrovnik',
    country: 'Croácia',
    countryCode: 'HR',
    description: 'Pérola do Adriático com muralhas medievais intactas, Cidade Antiga de pedra branca, praias cristalinas e Game of Thrones.',
    imageUrl: 'https://images.unsplash.com/photo-1516283119-a222bbb3ee95?w=800',
    climate: 'temperado',
    tags: ['praia', 'histórico', 'cidade', 'fotografia', 'mergulho', 'romântico'],
    latitude: 42.6507, longitude: 18.0944, featured: true,
  },
  {
    id: 'tallinn',
    name: 'Tallinn',
    country: 'Estónia',
    countryCode: 'EE',
    description: 'Uma das Cidades Velhas medievais mais bem preservadas da Europa, com castelo, igrejas góticas e start-ups digitais.',
    imageUrl: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800',
    climate: 'frio',
    tags: ['cidade', 'histórico', 'cultura', 'fotografia', 'económico', 'único'],
    latitude: 59.4370, longitude: 24.7536, featured: false,
  },
  {
    id: 'edimburgo',
    name: 'Edimburgo',
    country: 'Reino Unido',
    countryCode: 'GB',
    description: 'Capital escocesa com castelo imponente, Royal Mile, Festival Fringe, whisky, Highlands a horas e paisagens dramáticas.',
    imageUrl: 'https://images.unsplash.com/photo-1562607635-8b0ceb3e9cb2?w=800',
    climate: 'frio',
    tags: ['cidade', 'histórico', 'cultura', 'natureza', 'fotografia', 'festivais'],
    latitude: 55.9533, longitude: -3.1883, featured: false,
  },
  {
    id: 'madeira',
    name: 'Madeira',
    country: 'Portugal',
    countryCode: 'PT',
    description: 'Ilha atlântica com levadas entre florestas laurissilva, floricultura, vinho Madeira, poncha e clima primavera eterna.',
    imageUrl: 'https://images.unsplash.com/photo-1548263594-b7735e20b2f9?w=800',
    climate: 'tropical',
    tags: ['natureza', 'trekking', 'praia', 'gastronomia', 'fotografia', 'único'],
    latitude: 32.7607, longitude: -16.9595, featured: false,
  },
  {
    id: 'split',
    name: 'Split',
    country: 'Croácia',
    countryCode: 'HR',
    description: 'Segunda maior cidade croata com o Palácio de Diocleciano habitado, Riviera Dálmata e ilhas de Hvar e Brač próximas.',
    imageUrl: 'https://images.unsplash.com/photo-1571086932-8dd9a9c27e87?w=800',
    climate: 'temperado',
    tags: ['praia', 'histórico', 'cultura', 'fotografia', 'ilha', 'económico'],
    latitude: 43.5081, longitude: 16.4402, featured: false,
  },

  // ── NEW ASIA ──────────────────────────────────────────────────────────────
  {
    id: 'bangkok',
    name: 'Bangkok',
    country: 'Tailândia',
    countryCode: 'TH',
    description: 'Capital tailandesa frenética com Palácio Real, templos budistas dourados, street food incrível e vida noturna lendária.',
    imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800',
    climate: 'tropical',
    tags: ['cidade', 'cultura', 'gastronomia', 'templos', 'fotografia', 'compras'],
    latitude: 13.7563, longitude: 100.5018, featured: true,
  },
  {
    id: 'hoi-an',
    name: 'Hoi An',
    country: 'Vietname',
    countryCode: 'VN',
    description: 'Cidade antiga Património UNESCO com lanternas coloridas, casas comerciais históricas, alfaiates e praias próximas.',
    imageUrl: 'https://images.unsplash.com/photo-1583417417-6a0a1d0c2f49?w=800',
    climate: 'tropical',
    tags: ['cultura', 'histórico', 'gastronomia', 'fotografia', 'artesanato', 'romântico'],
    latitude: 15.8800, longitude: 108.3380, featured: true,
  },
  {
    id: 'hanoi',
    name: 'Hanói',
    country: 'Vietname',
    countryCode: 'VN',
    description: 'Capital vietnamita com Lago Hoan Kiem, Cidade Antiga de 36 ruas, baía de Ha Long próxima e culinária de rua única.',
    imageUrl: 'https://images.unsplash.com/photo-1499652848595-abb36c33b658?w=800',
    climate: 'tropical',
    tags: ['cidade', 'cultura', 'gastronomia', 'histórico', 'fotografia', 'económico'],
    latitude: 21.0285, longitude: 105.8542, featured: false,
  },
  {
    id: 'seul',
    name: 'Seul',
    country: 'Coreia do Sul',
    countryCode: 'KR',
    description: 'Megalópole dinâmica com palácios da dinastia Joseon, K-pop, gastronomia de fusão, tecnologia e DMZ a norte.',
    imageUrl: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'gastronomia', 'tecnologia', 'k-pop', 'compras'],
    latitude: 37.5665, longitude: 126.9780, featured: true,
  },
  {
    id: 'osaka',
    name: 'Osaka',
    country: 'Japão',
    countryCode: 'JP',
    description: 'Cidade dos sabores do Japão com Dotonbori iluminado, castelo histórico, Kuromon Market e Universal Studios.',
    imageUrl: 'https://images.unsplash.com/photo-1590559899731-a382839e5549?w=800',
    climate: 'temperado',
    tags: ['cidade', 'gastronomia', 'cultura', 'fotografia', 'família', 'entretenimento'],
    latitude: 34.6937, longitude: 135.5023, featured: false,
  },
  {
    id: 'pequim',
    name: 'Pequim',
    country: 'China',
    countryCode: 'CN',
    description: 'Capital milenar com a Grande Muralha, Cidade Proibida, Templo do Céu, Pato de Pequim e hutongs históricos.',
    imageUrl: 'https://images.unsplash.com/photo-1508804185872-d7badbc85330?w=800',
    climate: 'temperado',
    tags: ['cidade', 'histórico', 'cultura', 'gastronomia', 'fotografia', 'monumental'],
    latitude: 39.9042, longitude: 116.4074, featured: false,
  },
  {
    id: 'xangai',
    name: 'Xangai',
    country: 'China',
    countryCode: 'CN',
    description: 'Metrópole do futuro com Bund histórico, skyline de Pudong, culinária de fusão e arte contemporânea.',
    imageUrl: 'https://images.unsplash.com/photo-1474181487882-5abf3f0d3a8e?w=800',
    climate: 'temperado',
    tags: ['cidade', 'tecnologia', 'gastronomia', 'arte', 'fotografia', 'compras'],
    latitude: 31.2304, longitude: 121.4737, featured: false,
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    country: 'Índia',
    countryCode: 'IN',
    description: 'Coração financeiro da Índia com Gateway of India, Dharavi, Bollywood, mercados caóticos e frutos do mar.',
    imageUrl: 'https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=800',
    climate: 'tropical',
    tags: ['cidade', 'cultura', 'gastronomia', 'histórico', 'fotografia', 'contraste'],
    latitude: 19.0760, longitude: 72.8777, featured: false,
  },
  {
    id: 'goa',
    name: 'Goa',
    country: 'Índia',
    countryCode: 'IN',
    description: 'Paraíso costeiro indiano com praias tropicais, influência portuguesa, igrejas patrimônio, cashew feni e festas.',
    imageUrl: 'https://images.unsplash.com/photo-1559627260-1249ad5b4bff?w=800',
    climate: 'tropical',
    tags: ['praia', 'cultura', 'gastronomia', 'histórico', 'festas', 'económico'],
    latitude: 15.2993, longitude: 74.1240, featured: false,
  },
  {
    id: 'nova-delhi',
    name: 'Nova Delhi',
    country: 'Índia',
    countryCode: 'IN',
    description: 'Capital indiana com Qutb Minar, Red Fort, Humayun\'s Tomb, mercados Chandni Chowk e gastronomia Mughal.',
    imageUrl: 'https://images.unsplash.com/photo-1548013441-c524f2c5b7d7?w=800',
    climate: 'árido',
    tags: ['cidade', 'histórico', 'cultura', 'gastronomia', 'fotografia', 'patrimônio'],
    latitude: 28.6139, longitude: 77.2090, featured: false,
  },
  {
    id: 'katmandu',
    name: 'Katmandu',
    country: 'Nepal',
    countryCode: 'NP',
    description: 'Capital espiritual com Boudhanath e Pashupatinath, ponto de partida para o Everest e Annapurna, cultura nepalesa única.',
    imageUrl: 'https://images.unsplash.com/photo-1544274023-fdc0d5d30291?w=800',
    climate: 'temperado',
    tags: ['cultura', 'aventura', 'trekking', 'espiritual', 'fotografia', 'único'],
    latitude: 27.7172, longitude: 85.3240, featured: false,
  },
  {
    id: 'sri-lanka',
    name: 'Sri Lanka',
    country: 'Sri Lanka',
    countryCode: 'LK',
    description: 'Ilha do Índico com Sigiriya, plantações de chá, elefantes selvagens, praias tropicais e budismo vivo.',
    imageUrl: 'https://images.unsplash.com/photo-1575333953-3c49e5562a4c?w=800',
    climate: 'tropical',
    tags: ['natureza', 'cultura', 'aventura', 'praia', 'wildlife', 'espiritual'],
    latitude: 7.8731, longitude: 80.7718, featured: false,
  },
  {
    id: 'palawan',
    name: 'Palawan',
    country: 'Filipinas',
    countryCode: 'PH',
    description: 'Joia das Filipinas com lagunas de El Nido, rio subterrâneo de Puerto Princesa e praias de areia branca isoladas.',
    imageUrl: 'https://images.unsplash.com/photo-1559628133-c4f68ae1a7c8?w=800',
    climate: 'tropical',
    tags: ['praia', 'natureza', 'mergulho', 'aventura', 'fotografia', 'único'],
    latitude: 9.8349, longitude: 118.7384, featured: true,
  },
  {
    id: 'kuala-lumpur',
    name: 'Kuala Lumpur',
    country: 'Malásia',
    countryCode: 'MY',
    description: 'Capital malaia com Torres Petronas, Batu Caves, Chinatown histórico, street food e natureza tropical a minutos.',
    imageUrl: 'https://images.unsplash.com/photo-1596422846543-ab28aeef6d9c?w=800',
    climate: 'tropical',
    tags: ['cidade', 'gastronomia', 'cultura', 'compras', 'fotografia', 'económico'],
    latitude: 3.1390, longitude: 101.6869, featured: false,
  },
  {
    id: 'siem-reap',
    name: 'Siem Reap',
    country: 'Camboja',
    countryCode: 'KH',
    description: 'Portal para Angkor Wat, maior complexo religioso do mundo, com sunrises mágicos, temples na selva e cultura khmer.',
    imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800',
    climate: 'tropical',
    tags: ['histórico', 'cultura', 'fotografia', 'aventura', 'único', 'espiritual'],
    latitude: 13.3633, longitude: 103.8560, featured: true,
  },
  {
    id: 'ho-chi-minh',
    name: 'Ho Chi Minh',
    country: 'Vietname',
    countryCode: 'VN',
    description: 'Antiga Saigão com energia frenética, Túneis de Cu Chi, Notre-Dame vietnamita, street food e Rio Mekong próximo.',
    imageUrl: 'https://images.unsplash.com/photo-1619546952812-50c30dc04c84?w=800',
    climate: 'tropical',
    tags: ['cidade', 'histórico', 'cultura', 'gastronomia', 'fotografia', 'económico'],
    latitude: 10.8231, longitude: 106.6297, featured: false,
  },

  // ── NEW AMERICAS ──────────────────────────────────────────────────────────
  {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    country: 'Argentina',
    countryCode: 'AR',
    description: 'Paris da América do Sul com tango nas ruas, churrasco, bairros de La Boca e Palermo, Teatro Colón e vida noturna.',
    imageUrl: 'https://images.unsplash.com/photo-1568306986206-d1d01ee0a5c2?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'gastronomia', 'música', 'fotografia', 'vida noturna'],
    latitude: -34.6037, longitude: -58.3816, featured: false,
  },
  {
    id: 'santiago',
    name: 'Santiago',
    country: 'Chile',
    countryCode: 'CL',
    description: 'Capital chilena entre a cordilheira dos Andes e o oceano Pacífico, vinhos de classe mundial, Atacama e Patagónia próximas.',
    imageUrl: 'https://images.unsplash.com/photo-1555448473-e1b5e4b2c90c?w=800',
    climate: 'temperado',
    tags: ['cidade', 'natureza', 'gastronomia', 'vinho', 'aventura', 'fotografia'],
    latitude: -33.4489, longitude: -70.6693, featured: false,
  },
  {
    id: 'cartagena',
    name: 'Cartagena',
    country: 'Colômbia',
    countryCode: 'CO',
    description: 'Joia colonial colombiana com muralhas históricas, casas coloridas, praias caribenhas, cumbia e gastronomia de mar.',
    imageUrl: 'https://images.unsplash.com/photo-1583119393-46d5e8ce46e0?w=800',
    climate: 'tropical',
    tags: ['cidade', 'histórico', 'praia', 'gastronomia', 'fotografia', 'romântico'],
    latitude: 10.3910, longitude: -75.4794, featured: true,
  },
  {
    id: 'lima',
    name: 'Lima',
    country: 'Peru',
    countryCode: 'PE',
    description: 'Capital peruana com culinária eleita melhor da América Latina, centro histórico colonial, Miraflores e Barranco boémios.',
    imageUrl: 'https://images.unsplash.com/photo-1526650978544-43bd0f1db09b?w=800',
    climate: 'árido',
    tags: ['cidade', 'gastronomia', 'cultura', 'histórico', 'fotografia', 'arte'],
    latitude: -12.0464, longitude: -77.0428, featured: false,
  },
  {
    id: 'cidade-do-mexico',
    name: 'Cidade do México',
    country: 'México',
    countryCode: 'MX',
    description: 'Megacidade vibrante com museu Frida Kahlo, Teotihuacán, Zócalo colonial, mezcal, tacos e arte muralista.',
    imageUrl: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'gastronomia', 'histórico', 'arte', 'fotografia'],
    latitude: 19.4326, longitude: -99.1332, featured: false,
  },
  {
    id: 'havana',
    name: 'Havana',
    country: 'Cuba',
    countryCode: 'CU',
    description: 'Capital cubana congelada no tempo com carros americanos dos anos 50, música de salsa, Malecón e rum Havana Club.',
    imageUrl: 'https://images.unsplash.com/photo-1519077933282-c8a70b41e47b?w=800',
    climate: 'tropical',
    tags: ['cidade', 'histórico', 'cultura', 'música', 'fotografia', 'único'],
    latitude: 23.1136, longitude: -82.3666, featured: true,
  },
  {
    id: 'costa-rica',
    name: 'Costa Rica',
    country: 'Costa Rica',
    countryCode: 'CR',
    description: 'Paraíso de biodiversidade com florestas tropicais, vulcões ativos, praias do Pacífico e Atlântico, preguiças e jaguares.',
    imageUrl: 'https://images.unsplash.com/photo-1469560468518-fa3e791f6f8a?w=800',
    climate: 'tropical',
    tags: ['natureza', 'aventura', 'wildlife', 'praia', 'trekking', 'ecologia'],
    latitude: 9.7489, longitude: -83.7534, featured: false,
  },
  {
    id: 'galapagos',
    name: 'Galápagos',
    country: 'Equador',
    countryCode: 'EC',
    description: 'Laboratório de Darwin com iguanas marinhas, tartarugas gigantes, leões marinhos, pássaros únicos e snorkel espetacular.',
    imageUrl: 'https://images.unsplash.com/photo-1516589178581-6cd256faebda?w=800',
    climate: 'tropical',
    tags: ['natureza', 'wildlife', 'mergulho', 'fotografia', 'aventura', 'único'],
    latitude: -0.9538, longitude: -90.9656, featured: true,
  },
  {
    id: 'salar-de-uyuni',
    name: 'Salar de Uyuni',
    country: 'Bolívia',
    countryCode: 'BO',
    description: 'O maior deserto de sal do mundo, com espelhos de água na época das chuvas, flamingos e paisagens de outro planeta.',
    imageUrl: 'https://images.unsplash.com/photo-1511884642898-b6e75c3ec576?w=800',
    climate: 'árido',
    tags: ['natureza', 'fotografia', 'aventura', 'único', 'wildlife', 'paisagem'],
    latitude: -20.1338, longitude: -67.4891, featured: true,
  },
  {
    id: 'salvador',
    name: 'Salvador',
    country: 'Brasil',
    countryCode: 'BR',
    description: 'Capital afro-brasileira com Pelourinho colonial, axé, capoeira, acarajé, Carnival animado e praias de Itacaré.',
    imageUrl: 'https://images.unsplash.com/photo-1551038963-f88de57af8ae?w=800',
    climate: 'tropical',
    tags: ['cultura', 'música', 'gastronomia', 'praia', 'histórico', 'festivais'],
    latitude: -12.9714, longitude: -38.5014, featured: false,
  },
  {
    id: 'foz-do-iguacu',
    name: 'Foz do Iguaçu',
    country: 'Brasil',
    countryCode: 'BR',
    description: 'Uma das maiores maravilhas naturais do mundo: 275 quedas de água na fronteira Brasil-Argentina-Paraguai.',
    imageUrl: 'https://images.unsplash.com/photo-1504608252638-cf9d6e1baacc?w=800',
    climate: 'tropical',
    tags: ['natureza', 'fotografia', 'aventura', 'família', 'único', 'patrimônio'],
    latitude: -25.6953, longitude: -54.4367, featured: false,
  },

  // ── NEW AFRICA ────────────────────────────────────────────────────────────
  {
    id: 'cidade-do-cabo',
    name: 'Cidade do Cabo',
    country: 'África do Sul',
    countryCode: 'ZA',
    description: 'Cidade espetacular com Table Mountain, Cape Winelands, pinguins de Boulders Beach e rota dos jardins Garden Route.',
    imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800',
    climate: 'temperado',
    tags: ['cidade', 'natureza', 'praia', 'vinho', 'fotografia', 'aventura'],
    latitude: -33.9249, longitude: 18.4241, featured: true,
  },
  {
    id: 'zanzibar',
    name: 'Zanzibar',
    country: 'Tanzânia',
    countryCode: 'TZ',
    description: 'Ilha das Especiarias com praias paradisíacas, Stone Town histórico, recifes de coral e o aroma da baunilha no ar.',
    imageUrl: 'https://images.unsplash.com/photo-1582560568505-f4cf7b03b3b0?w=800',
    climate: 'tropical',
    tags: ['praia', 'histórico', 'mergulho', 'cultura', 'fotografia', 'romântico'],
    latitude: -6.1659, longitude: 39.2026, featured: true,
  },
  {
    id: 'cairo',
    name: 'Cairo',
    country: 'Egito',
    countryCode: 'EG',
    description: 'Pirâmides de Gizé, Esfinge, Museu Egípcio com Tutankhamun, bazar Khan el-Khalili e a magia do Nilo.',
    imageUrl: 'https://images.unsplash.com/photo-1503023645-5e2e56fde5c4?w=800',
    climate: 'árido',
    tags: ['histórico', 'cultura', 'gastronomia', 'fotografia', 'patrimônio', 'único'],
    latitude: 30.0444, longitude: 31.2357, featured: true,
  },
  {
    id: 'mauricia',
    name: 'Maurícias',
    country: 'Maurícias',
    countryCode: 'MU',
    description: 'Joia do Índico com lagunas turquesa, resorts de luxo, mergulho entre recifes, golf e gastronomia multicultural.',
    imageUrl: 'https://images.unsplash.com/photo-1544733094-e73c11e06284?w=800',
    climate: 'tropical',
    tags: ['praia', 'luxo', 'mergulho', 'romântico', 'gastronomia', 'natureza'],
    latitude: -20.3484, longitude: 57.5522, featured: false,
  },
  {
    id: 'seychelles',
    name: 'Seychelles',
    country: 'Seychelles',
    countryCode: 'SC',
    description: 'Arquipélago índico com praias de granito rosado, tartarugas gigantes de Aldabra, águas cristalinas e resorts exclusivos.',
    imageUrl: 'https://images.unsplash.com/photo-1548690312-1f538be25ebe?w=800',
    climate: 'tropical',
    tags: ['praia', 'luxo', 'mergulho', 'natureza', 'wildlife', 'romântico'],
    latitude: -4.6796, longitude: 55.4920, featured: false,
  },
  {
    id: 'tunes',
    name: 'Tunes',
    country: 'Tunísia',
    countryCode: 'TN',
    description: 'Capital tunisina com medina Património UNESCO, Cartagena romana, deserto do Saara acessível e hospitalidade árabe.',
    imageUrl: 'https://images.unsplash.com/photo-1484980959492-41dba97ea38c?w=800',
    climate: 'árido',
    tags: ['histórico', 'cultura', 'gastronomia', 'natureza', 'económico', 'patrimônio'],
    latitude: 36.8065, longitude: 10.1815, featured: false,
  },
  {
    id: 'kigali',
    name: 'Kigali',
    country: 'Ruanda',
    countryCode: 'RW',
    description: 'Capital mais limpa e segura de África, porta para o trekking de gorilas das montanhas, lagos e colinas verdejantes.',
    imageUrl: 'https://images.unsplash.com/photo-1617391543-d2c02b59af07?w=800',
    climate: 'tropical',
    tags: ['natureza', 'wildlife', 'cultura', 'aventura', 'único', 'ecoturismo'],
    latitude: -1.9441, longitude: 30.0619, featured: false,
  },
  {
    id: 'acra',
    name: 'Acra',
    country: 'Gana',
    countryCode: 'GH',
    description: 'Capital vibrante da África Ocidental com fortes coloniais, art scene emergente, praia Labadi e gastronomia ghanesa.',
    imageUrl: 'https://images.unsplash.com/photo-1524746045970-ebca24fd8e01?w=800',
    climate: 'tropical',
    tags: ['cultura', 'histórico', 'gastronomia', 'música', 'praia', 'único'],
    latitude: 5.5600, longitude: -0.1969, featured: false,
  },

  // ── NEW MIDDLE EAST ───────────────────────────────────────────────────────
  {
    id: 'tel-aviv',
    name: 'Tel Aviv',
    country: 'Israel',
    countryCode: 'IL',
    description: 'Cidade que nunca dorme com Bauhaus White City, praias mediterrânicas, gastronomia israelita e Jaffa histórica ao lado.',
    imageUrl: 'https://images.unsplash.com/photo-1543966888-7f1d81571c02?w=800',
    climate: 'temperado',
    tags: ['cidade', 'praia', 'gastronomia', 'cultura', 'vida noturna', 'fotografia'],
    latitude: 32.0853, longitude: 34.7818, featured: false,
  },
  {
    id: 'petra',
    name: 'Petra',
    country: 'Jordânia',
    countryCode: 'JO',
    description: 'Cidade rosa esculpida na rocha pelos Nabateus, uma das 7 maravilhas do mundo moderno e Património UNESCO.',
    imageUrl: 'https://images.unsplash.com/photo-1548879244-8ade9d06e3f8?w=800',
    climate: 'árido',
    tags: ['histórico', 'aventura', 'fotografia', 'cultura', 'único', 'patrimônio'],
    latitude: 30.3285, longitude: 35.4444, featured: true,
  },
  {
    id: 'muscat',
    name: 'Muscat',
    country: 'Omã',
    countryCode: 'OM',
    description: 'Capital omani com a Grande Mesquita do Sultão Qaboos, souks, praias isoladas, fiordes de Musandam e deserto.',
    imageUrl: 'https://images.unsplash.com/photo-1580476282557-d60bffa85ebb?w=800',
    climate: 'árido',
    tags: ['cidade', 'histórico', 'gastronomia', 'natureza', 'praia', 'único'],
    latitude: 23.5880, longitude: 58.3829, featured: false,
  },
  {
    id: 'doha',
    name: 'Doha',
    country: 'Catar',
    countryCode: 'QA',
    description: 'Metrópole do Golfo com Museu de Arte Islâmica, Souk Waqif histórico, skyline futurista e hospitalidade árabe única.',
    imageUrl: 'https://images.unsplash.com/photo-1553913861-4b8b26c51c13?w=800',
    climate: 'árido',
    tags: ['cidade', 'luxo', 'cultura', 'gastronomia', 'fotografia', 'compras'],
    latitude: 25.2854, longitude: 51.5310, featured: false,
  },
  {
    id: 'riade',
    name: 'Riade',
    country: 'Arábia Saudita',
    countryCode: 'SA',
    description: 'Capital saudita com AlUla arqueológico, Edge of the World, Diriyah histórico, cozinha regional e visão Saudi 2030.',
    imageUrl: 'https://images.unsplash.com/photo-1547448236-296e6c32c60d?w=800',
    climate: 'árido',
    tags: ['histórico', 'cultura', 'gastronomia', 'aventura', 'único', 'fotografia'],
    latitude: 24.7136, longitude: 46.6753, featured: false,
  },

  // ── NEW OCEANIA ───────────────────────────────────────────────────────────
  {
    id: 'melbourne',
    name: 'Melbourne',
    country: 'Austrália',
    countryCode: 'AU',
    description: 'Capital cultural australiana com street art em Hosier Lane, food scene multicultural, Great Ocean Road próxima.',
    imageUrl: 'https://images.unsplash.com/photo-1569777727399-7cf77f952f16?w=800',
    climate: 'temperado',
    tags: ['cidade', 'cultura', 'gastronomia', 'arte', 'fotografia', 'natureza'],
    latitude: -37.8136, longitude: 144.9631, featured: false,
  },
  {
    id: 'fiji',
    name: 'Fiji',
    country: 'Fiji',
    countryCode: 'FJ',
    description: 'Arquipélago polinésio com 333 ilhas, mergulho em recifes de coral, cultura Fijiana, kava e resorts de bungalow.',
    imageUrl: 'https://images.unsplash.com/photo-1559628129-0011f26c1ef6?w=800',
    climate: 'tropical',
    tags: ['praia', 'mergulho', 'natureza', 'cultura', 'relaxamento', 'romântico'],
    latitude: -17.7134, longitude: 178.0650, featured: false,
  },
  {
    id: 'bora-bora',
    name: 'Bora Bora',
    country: 'Polinésia Francesa',
    countryCode: 'PF',
    description: 'Pérola do Pacífico Sul com laguna turquesa incomparável, bangalôs sobre a água, Monte Otemanu e vida marinha única.',
    imageUrl: 'https://images.unsplash.com/photo-1515518679-8f0b6e7a6b62?w=800',
    climate: 'tropical',
    tags: ['praia', 'luxo', 'mergulho', 'romântico', 'fotografia', 'único'],
    latitude: -16.5004, longitude: -151.7415, featured: true,
  },
];

async function main() {
  console.log('A popular a base de dados...');

  for (const { id, ...data } of destinations) {
    await prisma.destination.upsert({
      where: { id },
      update: data,
      create: { id, ...data },
    });
  }

  console.log(`✓ ${destinations.length} destinos criados/actualizados`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
